# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jechoque <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/18 01:16:51 by jechoque          #+#    #+#              #
#    Updated: 2017/07/18 19:43:37 by jechoque         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_advanced_do-op
SRC = ./*.c
HDR = ./
FLAG = -Wall -Wextra -Werror

all :
		@gcc -o $(NAME) $(FLAG) $(SRC)

clean :
		@rm -f $(NAME)

re : clean all
