# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jechoque <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/20 10:25:30 by jechoque          #+#    #+#              #
#    Updated: 2017/07/22 11:26:25 by jechoque         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_tail
SRC = ./*c
OBJ = ./*o
HDR = ./
FLAG = -Wall -Wextra -Werror

all :
		@gcc -o $(NAME) $(FLAG) $(SRC)

clean :
		@rm -rf $(OBJ)

fclean : clean
		@rm -rf $(NAME)
